stages:
  - androidbuild
  - androidtest 
  
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - aremiasz_android_tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/geohunt/gradlew
  script:
    - cd Frontend/geohunt          # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build
  only:
    refs:
      - aremiasz_CICD
    #changes:
    #  - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - aremiasz_android_tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/geohunt/gradlew
  script:
    - cd Frontend/geohunt          # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - aremiasz_CICD
    #changes:
    #  - Frontend/**/*
