# DO NOT MERGE THIS FILE WITH MAIN

stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - evjulson_springboot_tag      # <-- change to your runner's tag
  script:
    - cd Backend/geolocation/Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - EVAN_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - evjulson_springboot_tag     # <-- change to your runner's tag
  script:
    - cd Backend/geolocation/Backend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - EVAN_CICD
    changes:
      - Backend/**/*

