stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - arjavtri_springboot_tag      # <-- change to your runner's tag
  script:
    - cd Backend/geolocation/Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - arjavtri_CICD
    changes:
      - Backend/**/*


maven-test:
  stage: maventest
  tags:
    - arjavtri_springboot_tag     # <-- change to your runner's tag
  script:
    - cd Backend/geolocation/Backend      # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - arjavtri_CICD
    changes:
      - Backend/**/*
